version: '2'

services:
  db:
    image: mysql:5.5.52
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sentinel
      MYSQL_DATABASE: sentinel_test
      MYSQL_USER: sentinel
      MYSQL_PASSWORD: sentinel

  dashd:
    logging:
      driver: none
    image: dashpay/dashd:testnet
    volumes:
      - sentinel-dashd-data:/dash
    ports:
      - 19999:19999
    environment:
      - RPCPASSWORD=bDEgk9YeqEPU9g6hqZFfCd3fHCCD4vQs

  sentinel:
    restart: always
    image: dashpay/sentinel:latest
    volumes:
      - "./conf/dash.conf:/sentinel/.dash/dash.conf"
    depends_on:
      - db
      - dashd
    environment:
      - DEBUG=false
      - RPCPASSWORD=bDEgk9YeqEPU9g6hqZFfCd3fHCCD4vQs

volumes:
    sentinel-dashd-data:  #declare a volume named sentinel-dashd-data