version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sentinel
      MYSQL_DATABASE: sentinel
      MYSQL_USER: sentinel
      MYSQL_PASSWORD: sentinel

  dashd:
    logging:
      driver: none
    image: dashpay/dashd
    volumes:
      - sentinel-dashd-data:/dash
    ports:
      - 9999:9999
    environment:
      - RPCPASSWORD=bDEgk9YeqEPU9g6hqZFfCd3fHCCD4vQs

  sentinel:
    restart: always
    image: dashpay/sentinel:latest
    depends_on:
    - db
    - dashd
    environment:
    - DEBUG=false

volumes:
    sentinel-dashd-data:  #declare a volume named sentinel-dashd-data